const express = require('express');
const router = express.Router();
const db = require('../database');
const automateEngine = require('../ontology/automate');
const { authenticateMiddleware } = require('../middleware/auth');
const { abacMiddleware } = require('../middleware/abac');

// GET List of Automate Rules
router.get('/rules', authenticateMiddleware, async (req, res) => {
  try {
    const rules = await db.getAutomations();
    res.json({
      success: true,
      count: rules.length,
      rules: rules.map(r => ({
        id: r.id,
        name: r.name,
        description: r.description,
        proposedActionType: r.proposed_action_type,
        conditionDefinition: typeof r.condition_definition === 'string' ? JSON.parse(r.condition_definition) : r.condition_definition,
        reviewRequired: Boolean(r.review_required),
        enabled: Boolean(r.enabled),
        createdBy: r.created_by,
        createdAt: r.created_at,
        updatedAt: r.updated_at
      }))
    });
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch automate rules', message: err.message });
  }
});

// POST Create or Update Automate Rule
router.post('/rules', authenticateMiddleware, abacMiddleware('ANALYTICAL_EXECUTION'), async (req, res) => {
  try {
    const { id, name, description, proposedActionType, conditionDefinition, enabled } = req.body;
    if (!name || !conditionDefinition) {
      return res.status(400).json({ error: 'name and conditionDefinition are required' });
    }

    const saved = await db.saveAutomation({
      id,
      name,
      description,
      proposedActionType: proposedActionType || 'FLAG_SUBJECT',
      conditionDefinition,
      reviewRequired: true,
      enabled: enabled !== false,
      createdBy: req.user.username
    });

    await db.logAudit(req.user.id, req.user.username, 'SAVE_AUTOMATE_RULE', 'AUTOMATE_ALERTING', `Saved automate rule ${name}`, saved.id);

    res.status(201).json({
      success: true,
      rule: {
        id: saved.id,
        name: saved.name,
        enabled: saved.enabled,
        updatedAt: saved.updated_at
      }
    });
  } catch (err) {
    res.status(500).json({ error: 'Failed to save automate rule', message: err.message });
  }
});

// POST Toggle Automate Rule Enable/Disable
router.post('/rules/:id/toggle', authenticateMiddleware, abacMiddleware('ANALYTICAL_EXECUTION'), async (req, res) => {
  try {
    const { enabled } = req.body;
    await db.toggleAutomation(req.params.id, Boolean(enabled));
    await db.logAudit(req.user.id, req.user.username, 'TOGGLE_AUTOMATE_RULE', 'AUTOMATE_ALERTING', `Toggled rule ${req.params.id} enabled=${enabled}`);
    res.json({ success: true, id: req.params.id, enabled: Boolean(enabled) });
  } catch (err) {
    res.status(500).json({ error: 'Failed to toggle automate rule', message: err.message });
  }
});

// POST Force Trigger Evaluation Pass
router.post('/evaluate', authenticateMiddleware, async (req, res) => {
  try {
    const proposals = await automateEngine.evaluateAutomations();
    res.json({
      success: true,
      evaluatedAt: new Date().toISOString(),
      newProposalsCount: proposals.length,
      proposals
    });
  } catch (err) {
    res.status(500).json({ error: 'Evaluation failed', message: err.message });
  }
});

// GET Fetch Pending Proposals generated by Automate
router.get('/proposals', authenticateMiddleware, async (req, res) => {
  try {
    const runs = await db.getAIRuns();
    const automateProposals = runs.filter(r => r.prompt_task === 'AUTOMATE_PROPOSED_ACTION' || r.model_id === 'AUTOMATE_ALERT_ENGINE_V1');
    res.json({
      success: true,
      count: automateProposals.length,
      proposals: automateProposals.map(p => ({
        id: p.id,
        promptTask: p.prompt_task,
        caseId: p.case_id,
        outputText: p.output_text,
        confidenceScore: p.confidence_score,
        reviewStatus: p.review_status,
        inputParams: typeof p.input_params === 'string' ? JSON.parse(p.input_params) : p.input_params,
        createdAt: p.created_at
      }))
    });
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch automate proposals', message: err.message });
  }
});

// GET SSE Event Stream for live proposals & alerts
router.get('/stream', (req, res) => {
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');

  res.write(`data: ${JSON.stringify({ type: 'CONNECTED', timestamp: new Date().toISOString() })}\n\n`);

  const unsubscribe = automateEngine.subscribe((data) => {
    res.write(`data: ${JSON.stringify(data)}\n\n`);
  });

  req.on('close', () => {
    unsubscribe();
  });
});

module.exports = router;
